# Generated by Django 6.0.2 on 2026-06-09 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_remove_order_orders_orde_referen_cf3026_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('tracking_id', models.CharField(blank=True, help_text='Courier tracking number e.g. DHL waybill number', max_length=100, null=True)),
                ('courier', models.CharField(blank=True, help_text='Courier name e.g. DHL, GIG Logistics, hand delivery', max_length=100, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Estimated date the item will reach the customer', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this delivery', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When vendor accepted and started processing', null=True)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='When vendor dispatched the order', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When customer confirmed delivery', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When order was cancelled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='delivery.delivery')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='delivery_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order'], name='delivery_order_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['delivery', 'timestamp'], name='delivery_history_idx'),
        ),
    ]
