# Generated by Django 6.0.2 on 2026-06-04 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_initial'),
        ('tenants', '0005_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('item_not_received', 'Item Not Received'), ('item_not_as_described', 'Item Not As Described'), ('wrong_item', 'Wrong Item Delivered'), ('damaged_item', 'Item Arrived Damaged'), ('unauthorized_charge', 'Unauthorized Charge'), ('duplicate_charge', 'Duplicate Charge'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('amount_disputed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('refund_issued', 'Refund Issued'), ('no_refund', 'No Refund'), ('partial_refund', 'Partial Refund'), ('escalated', 'Escalated')], max_length=20, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('evidence_note', models.TextField(blank=True, help_text='Customer-provided evidence description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='tenants.business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='orders.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='dispute_biz_status_idx'), models.Index(fields=['order'], name='dispute_order_idx'), models.Index(fields=['raised_by'], name='dispute_raised_by_idx')],
            },
        ),
    ]
