# Generated by Django 6.0.2 on 2026-08-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_disputeevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refund for partial refunds. Leave blank for full refund.', max_digits=12, null=True),
        ),
    ]
