# Generated by Django 6.0.2 on 2026-08-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_dispute_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='vendor_note',
            field=models.TextField(blank=True, help_text='Vendor response or additional context for admin review.', null=True),
        ),
    ]
