# Generated by Django 6.0.2 on 2026-06-05 07:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Platform commission rate as a decimal. 0.10 = 10%, 0.05 = 5%. Applied to every vendor settlement.', max_digits=5)),
                ('withdrawal_hold_days', models.PositiveIntegerField(default=7, help_text='Number of days funds must be held after a sale before a vendor can withdraw. Industry standard is 7 days.')),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum withdrawal amount in Naira. Prevents micro-withdrawals that incur unnecessary transfer fees.', max_digits=12)),
                ('auto_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Withdrawals at or above this amount (Naira) require manual admin approval before transfer is initiated. Default: ₦500,000.', max_digits=12)),
                ('fraud_failed_tx_threshold', models.PositiveIntegerField(default=3, help_text='Number of failed transactions within the lookback window that flags a withdrawal for admin review. Default: 3.')),
                ('fraud_lookback_hours', models.PositiveIntegerField(default=24, help_text='How many hours back to look when checking for suspicious failed transaction activity. Default: 24 hours.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who updated the platform configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
    ]
