# Generated by Django 6.0.2 on 2026-06-13 18:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='customer_confirm_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after shipping that customer has to confirm delivery. After this, delivery is auto-confirmed and escrow released.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='delivery_timeout_days',
            field=models.PositiveIntegerField(default=14, help_text='Days before an in_transit order is flagged for admin review if customer has not confirmed delivery.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dispute_resolution_days',
            field=models.PositiveIntegerField(default=7, help_text='Days admin has to resolve a dispute before it is auto-escalated.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dispute_window_days',
            field=models.PositiveIntegerField(default=3, help_text='Days after delivery confirmation that customer can raise a dispute. After this window, disputes are closed.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='escrow_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, vendor funds are held in escrow until the customer confirms delivery. Disabling releases funds immediately on payment.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='order_acceptance_days',
            field=models.PositiveIntegerField(default=2, help_text='Days vendor has to accept a paid order. After this, order is auto-cancelled and customer refunded.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='order_shipping_days',
            field=models.PositiveIntegerField(default=3, help_text='Days vendor has to ship after accepting. After this, order is auto-cancelled and customer refunded.'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='auto_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Withdrawals at or above this require manual admin approval.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Platform default commission rate. 0.10 = 10%.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='fraud_failed_tx_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Failed transactions within lookback window that triggers fraud flag.'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='fraud_lookback_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours to look back when checking for suspicious activity.'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='minimum_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum withdrawal amount in Naira.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_config_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='withdrawal_hold_days',
            field=models.PositiveIntegerField(default=7, help_text='Days funds must be held after escrow release before withdrawal.'),
        ),
    ]
