# Generated by Django 6.0.2 on 2026-06-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=20)),
                ('recipient_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenants.business')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='bankaccount_business_active_idx')],
            },
        ),
    ]
