# Generated by Django 6.0.2 on 2026-06-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_bankaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bankacct_active_idx',
            old_name='bankaccount_business_active_idx',
        ),
    ]
