# Generated by Django 6.0.2 on 2026-06-04 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_rename_bankaccount_business_active_idx_bankacct_active_idx'),
        ('transactions', '0004_webhookevent_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_audit', 'Pending Audit'), ('audit_failed', 'Audit Failed'), ('pending_hold', 'Pending Hold Period'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending_audit', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('audit_passed', models.BooleanField(blank=True, null=True)),
                ('audit_notes', models.TextField(blank=True, null=True)),
                ('requires_admin_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('transfer_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='tenants.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='tenants.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_request', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='wdl_business_date_idx'), models.Index(fields=['status'], name='wdl_status_idx'), models.Index(fields=['status', 'hold_expires_at'], name='wdl_hold_expiry_idx')],
            },
        ),
    ]
