# Generated by Django 6.0.2 on 2026-06-13 10:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional vendor-specific commission rate. Overrides category and platform default. 0.07 = 7%. Leave blank to use category or platform rate.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='escrow_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
