# Generated by Django 6.0.2 on 2026-06-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_tag_product_tags'),
        ('tenants', '0006_business_commission_rate_wallet_escrow_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStorefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='', help_text='Short description shown under your store name.', max_length=200)),
                ('accent_colour', models.CharField(default='#3b82f6', help_text='Hex colour code for your storefront theme, e.g. #3b82f6.', max_length=7)),
                ('banner_image', models.ImageField(blank=True, help_text='Recommended size: 1200 x 300px.', null=True, upload_to='storefront_banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='tenants.business')),
                ('featured_products', models.ManyToManyField(blank=True, help_text='Select up to 6 products to feature on your storefront.', related_name='featured_in_storefronts', to='products.product')),
            ],
        ),
    ]
