# Generated by Django 6.0.2 on 2026-06-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_orders_orde_referen_cf3026_idx'),
        ('tenants', '0006_business_commission_rate_wallet_escrow_balance'),
        ('transactions', '0004_webhookevent_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('hold', 'Hold'), ('release', 'Release')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_frozen', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_entries', to='tenants.business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_entries', to='orders.order')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_entries', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='escrow_biz_date_idx'), models.Index(fields=['order'], name='escrow_order_idx'), models.Index(fields=['is_frozen'], name='escrow_frozen_idx')],
            },
        ),
    ]
