# Generated by Django 6.0.2 on 2026-06-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_referen_cf3026_idx',
        ),
    ]
