# Generated by Django 6.0.2 on 2026-06-14 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_orders_orde_referen_cf3026_idx'),
        ('tenants', '0006_business_commission_rate_wallet_escrow_balance'),
        ('transactions', '0005_escrowentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The exact commission amount (Naira) taken from this order.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The commission rate actually applied to this order at settlement time.', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_date_idx'),
        ),
    ]
