# Generated by Django 6.0.2 on 2026-06-17 03:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_low_stock_threshold_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units currently available. Ignored if this product has variants.'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Optional variant-specific SKU, e.g. NIKE-AF1-WHT-42.', max_length=100, null=True, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to the base product price. Can be negative.', max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Units of this specific variant currently available.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Flag as low stock when this variant falls to or below this.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive variants are hidden from customers but preserved for order history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attribute type, e.g. Size, Colour, Material.', max_length=50)),
                ('value', models.CharField(help_text='Attribute value, e.g. 42, Black, Leather.', max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.productvariant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='variant_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='variantattribute',
            index=models.Index(fields=['variant'], name='variant_attr_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'name'), name='unique_attribute_per_variant'),
        ),
    ]
